name: CI
on:
  push:
    branches:
    - master
    - referenceImplementation
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run tests
        run: stack test
      - name: Check formatting
        run: make format-check
