name: CI
on:
  push:
    branches:
    - main
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Cache stack libraries
        uses: actions/cache@v2
        env:
          cache-name: cache-stack-snailscheme
        with:
          path: ~/.stack
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('stack.yaml.lock') }}

      - name: Run tests
        run: stack test

      - name: Install Nix
        uses: cachix/install-nix-action@v16

      - name: Check formatting
        run: nix-shell -p pkgs.haskellPackages.fourmolu --command 'make format-check'

      - name: Check hints
        run: nix-shell -p pkgs.haskellPackages.hlint --command 'make hlint'
