name: Run tests
on: [pull_request, push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install stack
        run: wget -qO- https://get.haskellstack.org | sh
      - name: Test
        run: stack test
